@startuml SoDoclass
 skinparam linetype ortho
' Dịch vụ du lịch ở đây bao gồm các khu vui chơi,
' ăn ngủ nghỉ, dịch vụ đi lại, các dịch vụ sẽ có loại DV
'Dịch vụ sẽ gồm có:
'1. Phương tiện để đi lại (gồm có phương tiện đi đến nơi du lịch và phương tiện đi lại ở điểm du lịch)
'2. Tham quan 
'3.ăn uống
'4. chỗ ngủ



class NhaCungCap{
  NhaCungCap_SoLuongDichVuCungCap: Int
}

class ChiTietNhaCungCap{
  ChiTietNhaCungCap_Id: String

}

class ThongTinDiaDiem{
  ThongTinDiaDiem_Id: String
  ThongTinDiaDiem_DiaChi: String
  ThongTinDiaDiem_Sdt: String
}
class TrangThaiHoatDong{
  TTHD_Id: String
  TTHD_Ten: String
}

class DuKhach{
  DuKhach_SDT: String
}
class LichTrinhDuLich{
  LichTrinhDuLich_Id: String
  LichTrinhDuLich_Ten: String 
  LichTrinhDuLich_NgayBatDau: Date 
  LichTrinhDuLich_NgayKetThuc: Date
}
class LichTrinhTrongNgay{
 LichTrinhTrongNgay_Id: String
 LichTrinhTrongNgay_NgayDi: Date

}

class KhachHang{
  KH_Id: String
  KH_MatKhau: String
  KH_HoTen: String
  KH_HinhAnh: String
  KH_Email: String

  
  DangNhap()
  DangXuat()
}

class LoaiKhachHang{

  LoaiKhachHang_Id: String
  LoaiKhachHang_Ten: String

}

class LoaIdichVu{
  LoaIdichVu_Id: String
  LoaIdichVu_Ten: String
}

class LoaiHinhDichVu{
  LoaiHinhDichVu_Id: String
  LoaiHinhDichVu_Ten: String
}
TrangThaiHoatDong "1"-"*" ThongTinDiaDiem

KhachHang "*"-"1" LoaiKhachHang

NhaCungCap "1"-"*" ChiTietNhaCungCap
ChiTietNhaCungCap "*"-"1" LoaIdichVu 
LoaIdichVu "1"--"*" LoaiHinhDichVu
ThongTinDiaDiem "*"-"1" NhaCungCap


LichTrinhDuLich "*"-"1" DuKhach
LichTrinhTrongNgay "*"-"1" LichTrinhDuLich
ThongTinDiaDiem "*"--"1" LichTrinhTrongNgay

NhaCungCap ---|> KhachHang
KhachHang <|-- DuKhach

@enduml