@startuml So Do class
 skinparam linetype ortho
' Dịch vụ du lịch ở đây bao gồm các khu vui chơi,
' ăn ngủ nghỉ, dịch vụ đi lại, các dịch vụ sẽ có loại DV
'Dịch vụ sẽ gồm có:
'1. Phương tiện để đi lại (gồm có phương tiện đi đến nơi du lịch và phương tiện đi lại ở điểm du lịch)
'2. Tham quan và ăn uống
'3. chỗ ngủ



class NHACUNGCAP{
  NCC_SOLUONGDICHVUCUNGCAP: Int
}

class CHITIETNHACUNGCAP{
  CTNCC_ID: String

}

class THONGTINDIADIEM{
  THONGTINDIADIEM_ID: String
  THONGTINDIADIEM_DIACHI: String
  THONGTINDIADIEM_SDT: String
}
class TRANGTHAIHOATDONG{
  TTHD_ID: String
  TTHD_Ten: String
}

class DUKHACH{
  DK_SDT: String
}
class LICHTRINHDULICH{
  LTDL_ID: String
  LTDL_TEN: String 
  LTDL_NGAYBATDAU: Date 
  LTDL_NGAYKETTHUC: Date
}
class LICHTRINHTRONGNGAY{
 CTLTDL_ID: String
 CTLTDL_NGAYDI: Date


}

' class chitiet{

' }

class KHACHHANG{
  KH_ID: String
  KH_MATKHAU: String
  KH_HoTen: String
  KH_HinhAnh: String
  KH_EMAIL: String

  
  DangNhap()
  DangXuat()
}

class LOAIKHACHHANG{

  LKH_ID: String
  LKH_TEN: String

}

class LOAIDICHVU{
  LDV_ID: String
  LDV_TEN: String
}

class LOAIHINHDICHVU{
  LHDV_ID: String
  LHDV_TEN: String
}
TRANGTHAIHOATDONG "1"-"*" THONGTINDIADIEM

KHACHHANG "*"-"1" LOAIKHACHHANG

NHACUNGCAP "1"-"*" CHITIETNHACUNGCAP
CHITIETNHACUNGCAP "*"-"1" LOAIDICHVU 
LOAIDICHVU "1"--"*" LOAIHINHDICHVU
THONGTINDIADIEM "*"-"1" NHACUNGCAP


LICHTRINHDULICH "*"-"1" DUKHACH
LICHTRINHTRONGNGAY "*"-"1" LICHTRINHDULICH
THONGTINDIADIEM "*"--"1" LICHTRINHTRONGNGAY

' THONGTINDIADIEM "*"-"1" chitiet
' chitiet "1"-"*" LICHTRINHTRONGNGAY

NHACUNGCAP ---|> KHACHHANG
KHACHHANG <|-- DUKHACH

@enduml