@startuml SoDoUC
left to right direction
actor "Quản lý" as QL
actor "Khách Hàng" as KH
actor "Nhà cung cấp" as NCC
actor "Du khách" as DKhach


rectangle  SoDoTongQuan{
  usecase "UC-8 Quản lý loại dịch vụ" as QLLDV
  usecase "UC-9 Quản lý loại hình dịch vụ" as QLLHDV
  usecase "UC-3 Quản lý thông tin điểm đến" as QLTTDD

  usecase "UC-4 Đăng ký địa điểm mới" as Them_TTDD
  usecase "UC-5 Cập nhật địa điểm " as CapNhat_TTDD
  usecase "UC-7 Cập nhật thông tin khách hàng" as CapNhat_TTKH

  usecase "UC-6 Quản lý thông tin khách hàng" as QLTTKH
  usecase "UC-1 Đăng ký" as DKy
  usecase "UC-2 Đăng nhập" as DNhap
  usecase "UC-10 Quản lý lịch trình chuyến đi" as QLCD
}
CapNhat_TTDD -- QLTTDD
Them_TTDD -- QLTTDD
QLTTKH - DKy
CapNhat_TTKH .> QLTTKH : extend

KH -- CapNhat_TTKH
KH -- DKy

QLTTDD - QL
QLLHDV ---- QL
QLTTKH - QL
QLLDV -- QL



NCC --|> KH

DKhach --|> KH

NCC - CapNhat_TTDD
NCC - Them_TTDD


DKhach -- QLCD

@enduml