@startuml Hệ Thống Sàn điện tử
left to right direction
actor "Nhà cung cấp DV" as NCC
actor "Quản lý" as QL
actor "Du khách" as DK
actor "Khách hàng" as KH 
rectangle DuLichDienTu {
  usecase "Cung cấp dịch vụ" as DV
  'Loại dv nằm trong
  ' usecase "Quản lý loại dịch vụ" as QLLDV
  usecase "Quản lý lịch trình du lịch" as QLLT
  usecase "Đăng Nhập" as DangNhap
  ' usecase "Biên Nhận" as BienNhan
  usecase "Thông tin cá nhân" as ThongTinCaNhan
  usecase "Thanh Toán" as TT
  usecase "Đăng Ký" as DangKy
  usecase "Nhà cung cấp dịch vụ" as DangKy_NCC
  usecase "du khách" as DangKy_DK
  usecase "Lịch trình du lịch" as LTDL
  usecase "Tài khoản khách hàng" as TK
  usecase "Loại dịch vụ" as LDV
  usecase "Quản lý nhà cung cấp" as QLNCC
  usecase "Địa điểm du lịch" as DD
}
DV <--- NCC
' QL --> QLLDV
QL --> QLNCC
QL --> QLLT
QL --> TK
QL --> LDV
QL --> DD

TT <-- DK
ThongTinCaNhan <-- DK  
LTDL <-- DK

QLLT ..> DangNhap : include
' QLLDV ..> DangNhap : include
QLNCC ..> DangNhap :include
DV .> DangNhap : include
TK ..> DangNhap : include
LDV ..> DangNhap : include

DangNhap <.. LTDL : include
DangNhap <.. ThongTinCaNhan : include
DangNhap <.. TT : include

KH--> DangKy
@enduml
