@startuml So Do class

' Dịch vụ du lịch ở đây bao gồm các khu vui chơi,
' ăn ngủ nghỉ, dịch vụ đi lại, các dịch vụ sẽ có loại DV
'Dịch vụ sẽ gồm có:
'1. Phương tiện để đi lại (gồm có phương tiện đi đến nơi du lịch và phương tiện đi lại ở điểm du lịch)
'2. Tham quan và ăn uống
'3. chỗ ngủ



Class DANHSACHDICHVU{
  DSDV_ID
  DSDV_TEN
  Them()
  Sua()
}

class NHACUNGCAP{
  NCC_ID
  NCC_Ten
  NCC_SOLUONGDICHVU
  NCC_DANHSACHDICHVU
  Them()
  Sua()
}

class LICHTRINHDULICH{
  LTDL_ID: String
  LTDL_Ten: String
  DK_HOTEN: String
  LTDL_NgayBatDau: String
  LTDL_NgayKetThuc: String


  Them()
  Sua()
  ThanhToan()
}


class DUKHACH{
  DK_TAIKHOAN: String
  DK_MATKHAU: String
  DK_HOTEN: String
  DK_NGAYSINH: Datetime
  DK_SDT: String
  SuaThongTin()
  ThanhToan()
}
Class THANHTOAN{}
Class CHITIETTHANHTOAN{

}

Class CUNGCAPDICHVU{
  CCDV_ID : String
  CCDV_Ten: StrinG
  CCDV_LOAIDICHVU: String
  CCDV_LoaiDV: String
}
'một lịch trình thì có 1-> n ngày, 1 ngày đi sẽ có nhiều dịch vụ bởi nhà cung cấp dv
'1 ncc_DVu -> cung cấp cho nhiều lịch trình 
'=> thực thể yếu => thêm chi tiết lịch trình du lịch mỗi ngày đi sẽ là 1 chi tiết

  ' chỗ rối ở đây nếu hôm nay đi 2 chỗ mai đi 4 chỗ thì ghi sao
class CHITIETLICHTRINHDULICH{
  CTLTDL_ID: String
  CTLTDL_NGAY: Datetime
  CTLTDL_DIADIEM: String
  CTLTDL_THANHPHO: String
}


'1 nhà cung cấp có thể có nhiều loại dịch vụ du lịch
class CHITIETDANHSACHDICHVU{
  CTDSDV_ID
  DSDV_ID
  NCC_ID
  
}

class DANHSACHDICHVU{}
' class PHUONGTIENDILAI{}
' Class ANUONGTHAMQUAN{}
' Class NGHINGOI{}


' ------------------

CHITIETDANHSACHDICHVU -- NHACUNGCAP
CHITIETDANHSACHDICHVU - DANHSACHDICHVU



' DUKHACH - LICHTRINHDULICH


' NHACUNGCAP - DANHSACHDICHVU
' LICHTRINHDULICH -- THANHTOAN
' THANHTOAN - CHITIETTHANHTOAN
' ' CHITIETTHANHTOAN --- CUNGCAPDICHVU
' LICHTRINHDULICH -- CHITIETLICHTRINHDULICH
' CHITIETLICHTRINHDULICH -- CUNGCAPDICHVU
' DANHSACHDICHVU -- CUNGCAPDICHVU

' CUNGCAPDICHVU <|-- NGHINGOI
' CUNGCAPDICHVU <|-- ANUONGTHAMQUAN
' CUNGCAPDICHVU <|-- PHUONGTIENDILAI

@enduml