@startuml SoDoUC
left to right direction
actor "Quản lý" as QL
actor "Nhà cung cấp" as NCC
actor "Du khách" as DKhach


rectangle  "HỆ THỐNG HỖ TRỢ DU LỊCH ĐIỆN TỬ KẾT HỢP CÁC DỊCH VỤ"{
  usecase "UC-9 Quản lý lịch trình du lịch" as QLCD
  
  usecase "UC-8 Quản lý loại dịch vụ" as QLLDV
  usecase "UC-3 Quản lý địa điểm" as QLDD
  ' usecase "UC-9 Quản lý thông tin " as QLTTDD

  usecase "UC-4 Đăng ký dịch vụ mới" as Them_TTDD
  usecase "UC-5 Cập nhật dịch vụ " as CapNhat_TTDD
  usecase "UC-7 Cập nhật thông tin khách hàng" as CapNhat_TTKH

  usecase "UC-6 Xem thông tin nhà cung cấp" as QLTTKH
  usecase "UC-1 Đăng ký" as DKy
  usecase "UC-2 Đăng nhập" as DNhap
  
  usecase "UC-10 Quản lý bài viết" as QLBV
  usecase "UC-11 Đánh giá chất lượng địa điểm" as DGCL
  usecase "UC-12 Gợi ý địa điểm du lịch" as GYDD


  
  ' chỗ nay nhà cung cấp và du khách đều dùng quản lý lịch trình du lịch
}



DKhach - CapNhat_TTKH
DKhach -- DKy

QLDD -- QL
QLTTKH -- QL
QLLDV -- QL
QLBV -- QL


NCC -|> DKhach


NCC - CapNhat_TTDD
NCC - Them_TTDD


DKhach - QLCD


DNhap <.. QLLDV : include
DNhap <.. QLBV : include
DNhap <.. QLDD : include
DNhap <.. QLTTKH : include

CapNhat_TTDD ..> DNhap : include
QLCD ..> DNhap : include
CapNhat_TTKH ..> DNhap : include
Them_TTDD ..> DNhap : includex


QLCD <.. DGCL: extend
QLCD <.. GYDD: extend
@enduml