@startuml SoDoUC
left to right direction
actor "Quản lý" as QL
actor "Khách Hàng" as KH
actor "Nhà cung cấp" as NCC
actor "Du khách" as DKhach


rectangle  "SO DO USECASE"{
  usecase "UC-8 Quản lý loại dịch vụ" as QLLDV
  usecase "UC-3 Quản lý địa điểm" as QLDD
  ' usecase "UC-9 Quản lý thông tin " as QLTTDD

  usecase "UC-4 Đăng ký dịch vụ mới" as Them_TTDD
  usecase "UC-5 Cập nhật dịch vụ " as CapNhat_TTDD
  usecase "UC-7 Cập nhật thông tin khách hàng" as CapNhat_TTKH

  usecase "UC-6 Quản lý thông tin khách hàng" as QLTTKH
  usecase "UC-1 Đăng ký" as DKy
  usecase "UC-2 Đăng nhập" as DNhapz
  usecase "UC-9 Quản lý lịch trình du lịch" as QLCD
  
  usecase "UC-10 Quản lý bài viết" as QLBV

  
  ' chỗ nay nhà cung cấp và du khách đều dùng quản lý lịch trình du lịch
}

QLTTKH - DKy
CapNhat_TTKH ..> QLTTKH : extend

KH -- CapNhat_TTKH
KH --- DKy

QLDD -- QL
QLTTKH -- QL
QLLDV - QL
QLBV -- QL


NCC -|> KH

DKhach ---|> KH

NCC - CapNhat_TTDD
NCC - Them_TTDD


DKhach -- QLCD

@enduml